version: "3.9"

services:
  eve-mariadb:
    image: mariadb:10.11.3
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: "1234"
      MARIADB_DATABASE: "eve-dev"
    volumes:
      - "mariadb-data:/var/lib/mysql:rw"
    networks:
      - eve-storage

  eve-phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8000:80"
    restart: "no"
    environment:
      PMA_HOST: "eve-mariadb"
      PMA_PORT: 3306
    networks:
      - eve-storage

  eve-elasticsearch:
    image: elasticsearch:8.7.1
    restart: "no"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
    volumes:
      - "elastic-data:/usr/share/elasticsearch/data:rw"
    networks:
      - eve-storage

  eve-kibana:
    image: kibana:8.7.1
    ports:
      - "5601:5601"
    restart: "no"
    environment:
      ELASTICSEARCH_HOSTS: "http://eve-elasticsearch:9200"
    networks:
      - eve-storage

  eve-redis:
    image: redis:7.0.2-alpine
    restart: "no"
    networks:
      - eve-storage

  eve-cli:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: "development"
    restart: "no"
    command: "sleep infinity"
    ports:
      - "3030:3030"
      - "3000:3000"
    env_file:
      - ".env"
    networks:
      - eve-storage
    volumes:
      - ".:/app"

networks:
  eve-storage:
    driver: "bridge"
    name: eve-storage

volumes:
  elastic-data:
  mariadb-data:
