version: "3.9"

services:
  eve-mariadb:
    image: mariadb:10.8.2
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: "1234"
      MARIADB_DATABASE: "eve-dev"
    volumes:
      - "./mariadb_data:/var/lib/mysql"
    networks:
      - eve-storage

  eve-phpmyadmin:
    image: phpmyadmin:5.1.1
    ports:
      - "8000:80"
    restart: "no"
    environment:
      PMA_HOST: "mariadb"
      PMA_PORT: 3306
    networks:
      - eve-storage

  eve-elasticsearch:
    image: elasticsearch:8.1.2
    restart: "no"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
    volumes:
      - "./elastic_data:/usr/share/elasticsearch/data"
    networks:
      - eve-storage

  eve-kibana:
    image: kibana:7.17.2
    ports:
      - "5601:5601"
    restart: "no"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - eve-storage

  eve-redis:
    image: redis:7.0.2-alpine
    restart: "no"
    networks:
      - eve-storage

  eve-rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    restart: "no"
    ports:
      - "15672:15672"
    networks:
      - eve-storage

  eve-cli:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: "development"
    restart: "no"
    command: "sleep infinity"
    env_file:
      - ".env"
    networks:
      - eve-storage

networks:
  eve-storage:
    driver: "bridge"
    name: eve-storage
